# Add 'label1' to any changes within 'examples' folder or any subfolders
area/docs:
  - docs/**/*
  - ./*.md

area/example:
  - hub/examples/**/*

area/housekeeping:
  - .github/**/*
  - ./.gitignore

area/hub:
  - hub/**/*

area/cicd:
  - .github/workflows/**/*
  - builder/**/*

component/executor:
  - hub/executors/**/*

component/encoder:
  - hub/executors/encoders/**/*

component/indexer:
  - hub/executors/indexers/**/*

component/ranker:
  - hub/executors/rankers/**/*

component/transformer:
  - hub/executors/transformers/**/*