!TransformerTextEncoder
metas:
  on_gpu: false
  batch_size: 4
  workspace: $TMP_WORKSPACE
  name: transformer_encoder
with:
  pooling_strategy: cls
  max_length: 8
  model_name: bert-base-uncased
requests:
  on:
    [SearchRequest, IndexRequest]:
      - !EncodeDriver
        with:
          method: encode

    ControlRequest:
      - !ControlReqDriver {}