name: CI

on: [pull_request]

jobs:
  hub-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: actions/hub-builder@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

